export const FETCH_ABOUT = 'FETCH_ABOUT';
export const ADD_ABOUT = 'ADD_ABOUT';
export const DELETE_ABOUT = 'DELETE_ABOUT';
export const EDIT_ABOUT = 'EDIT_ABOUT';
export const FETCH_CONTACTUS = 'FETCH_CONTACTUS';
export const ADD_CONTACTUS = 'ADD_CONTACTUS';
export const DELETE_CONTACTUS = 'DELETE_CONTACTUS';
export const EDIT_CONTACTUS = 'EDIT_CONTACTUS';
export const FETCH_RESOURCETEAM = 'FETCH_RESOURCETEAM';
export const ADD_RESOURCETEAM = 'ADD_RESOURCETEAM';
export const DELETE_RESOURCETEAM = 'DELETE_RESOURCETEAM';
export const EDIT_RESOURCETEAM = 'EDIT_RESOURCETEAM';
export const FETCH_SERVICES = 'FETCH_SERVICES';
export const ADD_SERVICE = 'ADD_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const FETCH_TOOLS = 'FETCH_TOOLS';
export const ADD_TOOL = 'ADD_TOOL';
export const DELETE_TOOL = 'DELETE_TOOL';
export const EDIT_TOOL = 'EDIT_TOOL';
export const ADD_CONTACTENQUIRE = 'ADD_CONTACTENQUIRE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const USER_LOADED = 'USER_LOADED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const FETCH_USERS = 'FETCH_USERS';

export const DELETE_USER = 'DELETE_USER';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const EMAIL_UPDATED = 'EMAIL_UPDATED';


export const ADD_USER = 'ADD_USER';
export const USER_LOADING = 'USER_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';



export const LOADING_ABOUT = 'LOADING_ABOUT';

export const RENTAL_ERROR = 'RENTAL_ERROR';
export const SUBMIT_RENTAL = 'SUBMIT_RENTAL';
export const SET_CONTACTUS_ACTIVE = 'SET_CONTACTUS_ACTIVE';


export const FETCH_TESTIMONIAL = 'FETCH_TESTIMONIAL';
export const ADD_TESTIMONIAL = 'ADD_TESTIMONIAL';
export const DELETE_TESTIMONIAL = 'DELETE_TESTIMONIAL';
export const EDIT_TESTIMONIAL = 'EDIT_TESTIMONIAL';

export const FETCH_SUBSCRIBER = 'FETCH_SUBSCRIBER';
export const ADD_SUBSCRIBER = 'ADD_SUBSCRIBER';
export const DELETE_SUBSCRIBER = 'DELETE_SUBSCRIBER';
export const EDIT_SUBSCRIBER = 'EDIT_SUBSCRIBER';

export const FETCH_TRAINING = 'FETCH_TRAINING';
export const ADD_TRAINING = 'ADD_TRAINING';
export const DELETE_TRAINING = 'DELETE_TRAINING';
export const EDIT_TRAINING = 'EDIT_TRAINING';

export const FETCH_REPAIR = 'FETCH_REPAIR';
export const ADD_REPAIR = 'ADD_REPAIR';
export const DELETE_REPAIR = 'DELETE_REPAIR';
export const EDIT_REPAIR = 'EDIT_REPAIR';

export const FETCH_FABRICATION = 'FETCH_FABRICATION';
export const ADD_FABRICATION = 'ADD_FABRICATION';
export const DELETE_FABRICATION = 'DELETE_FABRICATION';
export const EDIT_FABRICATION = 'EDIT_FABRICATION';

export const FETCH_CONSULTANCY = 'FETCH_CONSULTANCY';
export const ADD_CONSULTANCY = 'ADD_CONSULTANCY';
export const DELETE_CONSULTANCY = 'DELETE_CONSULTANCY';
export const EDIT_CONSULTANCY = 'EDIT_CONSULTANCY';